---
- hosts: all
  become: yes
  tasks: 
    - name: Install apache server
      yum: name=httpd state=present
    - name: Run apache server 
      service: name=httpd state=started
    - name: Run on Vm start
      service:  name=httpd enabled=yes
 
