---
- hosts: all
  become: yes
  vars_files: 
             - vars.yml 

  tasks:
  - include: inc1.yml
    when: ansible_os_family == "RedHat"
  - name: Start and enable apache server
    service: name=httpd state=started enabled=yes	
    when: ansible_os_family == "RedHat"
  - name: Clone code form github and deploy to apache
    git:
      repo: "{{git_url}}"
      dest: "{{deploy_path}}"
  - name: Restart apache server
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"    

#    -----WORKING THIS FILE---





