---
- hosts: all
  become: yes
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=present
  - name: Start and enable apache server
    service: name=httpd state=started enabled=yes	
  - name: Clone code form github and deploy to apache
    git:
      repo: 'https://github.com/javahometech/javahome-app'
      dest: /var/www/html
  - name: Restart apache server
    service: name=httpd state=restarted

#---
#- hosts: all
#  become: yes
#  tasks:
#  - name: ensure apache is at the latest version
#    yum: name=httpd state=present
#    service: 
#    name: httpd
#    state: started
#    enable: yes


