

#### it will not work with "YUM" but for refence of "when: ansible_os_famil" we can use this file

---
- hosts: all
  become: yes
  vars_files: 
             - vars.yml 

  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=present
    when: ansible_os_family == "Debian"
  - name: Start and enable apache server
    service: name=httpd state=started enabled=yes	
    when: ansible_os_family == "Debian"
  - name: Clone code form github and deploy to apache
    git:
      repo: "{{git_url}}"
      dest: "{{deploy_path}}"
  - name: Restart apache server
    service: name=httpd state=restarted
    when: ansible_os_family == "Debian"    

#    -----WORKING THIS FILE---





